# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chasqui/',
                'doc_host': 'https://GarciaJC.github.io',
                'git_url': 'https://github.com/GarciaJC/chasqui/',
                'lib_path': 'chasqui'},
  'syms': { 'chasqui.core': {'chasqui.core.foo': ('core.html#foo', 'chasqui/core.py')},
            'chasqui.sync': {'chasqui.sync.sync': ('sync.html#sync', 'chasqui/sync.py')}}}
